#!/usr/bin/env ruby

# Author: James Psota
# File:   determine_preprocessor_vars.rb 

# Copyright (c) 2024 James Psota
# __________________________________________

# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
# 
#   http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.



# generates preprocessor commands for command line input of compiler for Pure library options
# based on environment variables exported from the application-level Pure application Makefile

# require 'awesome_print'

private def deify(opts)
    opts.map{|k,v| "-D#{k}=#{v}"}.join(' ')
end

private def fail_out(msg)
    
    full_msg = <<-HEREDOC
    ***************************************************
    ***************************************************
    ***************************************************
 
    ====> #{msg} 
 
    ***************************************************
    ***************************************************
    ***************************************************

    HEREDOC

    require 'colorize'
    $stderr.puts full_msg.red
    exit 1
end

private def gen_pcv_vars(pcv)
    opts = case pcv
    # when 1
    #     {}

    # when 20
    #     {}
    # when 21
    #     {PCV2_OPTION_USE_FREELIST: 1, PCV2_OPTION_USE_PADDED_BUF_PTR: 0, PCV2_OPTION_PREVENT_MEMBER_FALSE_SHARING: 0, PCV2_OPTION_ACTIVE_PAUSE: 0}
    # when 22
    #     {PCV2_OPTION_USE_FREELIST: 1, PCV2_OPTION_USE_PADDED_BUF_PTR: 1, PCV2_OPTION_PREVENT_MEMBER_FALSE_SHARING: 0, PCV2_OPTION_ACTIVE_PAUSE: 0}
    # when 23
    #     {PCV2_OPTION_USE_FREELIST: 1, PCV2_OPTION_USE_PADDED_BUF_PTR: 0, PCV2_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV2_OPTION_ACTIVE_PAUSE: 0}
    # when 24
    #     {PCV2_OPTION_USE_FREELIST: 1, PCV2_OPTION_USE_PADDED_BUF_PTR: 1, PCV2_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV2_OPTION_ACTIVE_PAUSE: 0}
    # when 25
    #     {PCV2_OPTION_USE_FREELIST: 1, PCV2_OPTION_USE_PADDED_BUF_PTR: 1, PCV2_OPTION_PREVENT_MEMBER_FALSE_SHARING: 0, PCV2_OPTION_ACTIVE_PAUSE: 1}
    # when 26
    #     {PCV2_OPTION_USE_FREELIST: 1, PCV2_OPTION_USE_PADDED_BUF_PTR: 1, PCV2_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV2_OPTION_ACTIVE_PAUSE: 1}

    # when 30
    #     fail_out("PCV 30 not currently supported.")
    # when 32
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 0, PCV3_OPTION_ACTIVE_PAUSE: 0}
    # when 33
    #     fail_out("PCV 33 not currently supported.")
    # when 34
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 0}
    # when 35
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 0, PCV3_OPTION_ACTIVE_PAUSE: 1}
    # when 36
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1}

    when 40
        # For now, stick with PCV3 prefix on these options. After this finalizes, this should either be converted to a more
        # generic sounding prefix, or forked to PCV4, partially depending on if we fork untyped_producer_consumer_queue.h
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1, 
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 0}
    when 41
        # For now, stick with PCV3 prefix on these options. After this finalizes, this should either be converted to a more
        # generic sounding prefix, or forked to PCV4, partially depending on if we fork untyped_producer_consumer_queue.h
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 0}

    # meant to be a testing ground to run continuations but not collaboratively
    when 411
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1}

    when 42
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_SR_COLLAB: 1}
    when 43
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1, 
            PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_SR_COLLAB: 1}

    # Deprecated -- likely doesn't make sense
    # when 44
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_LOOK_AT_COUNT_APPR_1: 1}
    # when 45
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1, 
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_LOOK_AT_COUNT_APPR_1: 1}

    # WORK STEAL options *****************************
    # PCV4_OPTION_WS_SINGLE_CHUNK
    #  sub-options: PCV_4_NUM_CONT_CHUNKS
    when 460
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_LINEAR_PROBE: 1}
    when 461
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_RANDOM_PROBE: 1}
    when 462
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
            PCV4_ALLOW_CROSS_NUMA_STEAL: 1}
    when 463
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
            PCV4_ALLOW_CROSS_NUMA_STEAL: 0}
    when 464 # hyperthread-only steals
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
            PCV4_ALLOW_CROSS_NUMA_STEAL: 0, PCV4_STEAL_VICTIM_HYPERTHREAD_ONLY: 1}

    # Idential to the 46* block, but out-of-order enqueues and dequeues
    # BROKEN as of Dec 2019
    # when 470
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_LINEAR_PROBE: 1}
    # when 471
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_RANDOM_PROBE: 1}
    # when 472
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
    #         PCV4_ALLOW_CROSS_NUMA_STEAL: 1}
    # when 473
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_SINGLE_CHUNK: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
    #         PCV4_ALLOW_CROSS_NUMA_STEAL: 0}

    # PCV4_OPTION_WS_GSS
    #  sub-options: PCV_4_NUM_CONT_CHUNKS (Makefile) and RECEIVER_CHUNK_ALLOC_WEIGHT (pure_pipeline.h)
    when 480
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_GSS: 1, PCV4_STEAL_VICTIM_LINEAR_PROBE: 1}
    when 481
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_GSS: 1, PCV4_STEAL_VICTIM_RANDOM_PROBE: 1}
    when 482
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_GSS: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
            PCV4_ALLOW_CROSS_NUMA_STEAL: 1}
    when 483
        {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
            PCV4_OPTION_OOO_WAIT: 0, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
            PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_GSS: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
            PCV4_ALLOW_CROSS_NUMA_STEAL: 0}
            
    # Idential to the 48* block, but out-of-order enqueues and dequeues (not supported as of Dec 2019)
    # BROKEN as of Dec 2019
    # when 490
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_GSS: 1, PCV4_STEAL_VICTIM_LINEAR_PROBE: 1}
    # when 491
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_GSS: 1, PCV4_STEAL_VICTIM_RANDOM_PROBE: 1}
    # when 492
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_GSS: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
    #         PCV4_ALLOW_CROSS_NUMA_STEAL: 1}
    # when 493
    #     {PCV3_OPTION_USE_PADDED_RECORDS: 1, PCV3_OPTION_PREVENT_MEMBER_FALSE_SHARING: 1, PCV3_OPTION_ACTIVE_PAUSE: 1,
    #         PCV4_OPTION_OOO_WAIT: 1, PCV4_OPTION_EXECUTE_CONTINUATION: 1, PCV4_OPTION_EXECUTE_CONTINUATION_WORK_STEAL: 1,
    #         PCV4_OPTION_WS_PT_ACTIVE_WORK_BOOL_APPR_2: 1, PCV4_OPTION_WS_GSS: 1, PCV4_STEAL_VICTIM_NUMA_AWARE: 1,
    #         PCV4_ALLOW_CROSS_NUMA_STEAL: 0}

    else
        #$stderr.puts "*************************************************************************************************\n     Invalid PCV: #{pcv}".yellow
        {}
    end

    deify(opts)
end


private def main

    final_opts = []
    final_opts << gen_pcv_vars(ENV['PROCESS_CHANNEL_VERSION'].to_i)

    puts final_opts.join(' ')
end


main